#!/bin/sh

set -e

case "$1" in
  install|upgrade)
    if ! dpkg -l | grep -q '^.i *linux-udooneo'
      rm -f /usr/share/applications/ardublockly.desktop 
    fi
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
